---

- name: Include variables specific for the distribution.
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- import_tasks: install.yml
- import_tasks: configure.yml
